name: ter_code_backend
description: Backend para T3R-C0D3
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  postgres: ^2.6.2
  dotenv: ^4.1.0
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.8.2
  http: ^1.1.0
dev_dependencies:
  lints: ^2.1.1